//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManager.Services {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransportManager.Services.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AddCompany.
        /// </summary>
        internal static string Operation_AddCompany {
            get {
                return ResourceManager.GetString("Operation_AddCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AddDriver.
        /// </summary>
        internal static string Operation_AddDriver {
            get {
                return ResourceManager.GetString("Operation_AddDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AddUser.
        /// </summary>
        internal static string Operation_AddUser {
            get {
                return ResourceManager.GetString("Operation_AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AddVehicle.
        /// </summary>
        internal static string Operation_AddVehicle {
            get {
                return ResourceManager.GetString("Operation_AddVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DeleteCompanyByCompanyId.
        /// </summary>
        internal static string Operation_DeleteCompanyByCompanyId {
            get {
                return ResourceManager.GetString("Operation_DeleteCompanyByCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DeleteDriver.
        /// </summary>
        internal static string Operation_DeleteDriver {
            get {
                return ResourceManager.GetString("Operation_DeleteDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DeleteUser.
        /// </summary>
        internal static string Operation_DeleteUser {
            get {
                return ResourceManager.GetString("Operation_DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DeleteVehicle.
        /// </summary>
        internal static string Operation_DeleteVehicle {
            get {
                return ResourceManager.GetString("Operation_DeleteVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GetAllCompanies.
        /// </summary>
        internal static string Operation_GetAllCompanies {
            get {
                return ResourceManager.GetString("Operation_GetAllCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GetAllDrivers.
        /// </summary>
        internal static string Operation_GetAllDrivers {
            get {
                return ResourceManager.GetString("Operation_GetAllDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GetAllUsers.
        /// </summary>
        internal static string Operation_GetAllUsers {
            get {
                return ResourceManager.GetString("Operation_GetAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GetAllVehicles.
        /// </summary>
        internal static string Operation_GetAllVehicles {
            get {
                return ResourceManager.GetString("Operation_GetAllVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GetCompanyByCompanyId.
        /// </summary>
        internal static string Operation_GetCompanyByCompanyId {
            get {
                return ResourceManager.GetString("Operation_GetCompanyByCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GetDriver.
        /// </summary>
        internal static string Operation_GetDriver {
            get {
                return ResourceManager.GetString("Operation_GetDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GetManyDriversByCompanyId.
        /// </summary>
        internal static string Operation_GetManyDriversByCompanyId {
            get {
                return ResourceManager.GetString("Operation_GetManyDriversByCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GetManyVehicleByCompanyId.
        /// </summary>
        internal static string Operation_GetManyVehicleByCompanyId {
            get {
                return ResourceManager.GetString("Operation_GetManyVehicleByCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GetManyVehicleByDriverId.
        /// </summary>
        internal static string Operation_GetManyVehicleByDriverId {
            get {
                return ResourceManager.GetString("Operation_GetManyVehicleByDriverId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GetUserByLogin.
        /// </summary>
        internal static string Operation_GetUserByLogin {
            get {
                return ResourceManager.GetString("Operation_GetUserByLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GetVehicle.
        /// </summary>
        internal static string Operation_GetVehicle {
            get {
                return ResourceManager.GetString("Operation_GetVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        internal static string Operation_Login {
            get {
                return ResourceManager.GetString("Operation_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Register.
        /// </summary>
        internal static string Operation_Register {
            get {
                return ResourceManager.GetString("Operation_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RemoveCompanyByCompanyId.
        /// </summary>
        internal static string Operation_RemoveCompanyByCompanyId {
            get {
                return ResourceManager.GetString("Operation_RemoveCompanyByCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RemoveDriver.
        /// </summary>
        internal static string Operation_RemoveDriver {
            get {
                return ResourceManager.GetString("Operation_RemoveDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RemoveUser.
        /// </summary>
        internal static string Operation_RemoveUser {
            get {
                return ResourceManager.GetString("Operation_RemoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RemoveVehicle.
        /// </summary>
        internal static string Operation_RemoveVehicle {
            get {
                return ResourceManager.GetString("Operation_RemoveVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UpdateCompany.
        /// </summary>
        internal static string Operation_UpdateCompany {
            get {
                return ResourceManager.GetString("Operation_UpdateCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UpdateDriver.
        /// </summary>
        internal static string Operation_UpdateDriver {
            get {
                return ResourceManager.GetString("Operation_UpdateDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UpdateUser.
        /// </summary>
        internal static string Operation_UpdateUser {
            get {
                return ResourceManager.GetString("Operation_UpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UpdateVehicle.
        /// </summary>
        internal static string Operation_UpdateVehicle {
            get {
                return ResourceManager.GetString("Operation_UpdateVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fail.
        /// </summary>
        internal static string Status_Fail {
            get {
                return ResourceManager.GetString("Status_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not found.
        /// </summary>
        internal static string Status_NotFound {
            get {
                return ResourceManager.GetString("Status_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Success.
        /// </summary>
        internal static string Status_Success {
            get {
                return ResourceManager.GetString("Status_Success", resourceCulture);
            }
        }
    }
}
