//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManager.Data {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransportManager.Data.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Компания с указанным CompanyId уже существует.
        /// </summary>
        internal static string Error_CompanyIdExists {
            get {
                return ResourceManager.GetString("Error_CompanyIdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Компания с указанным CompanyId не найдена.
        /// </summary>
        internal static string Error_CompanyNotFound {
            get {
                return ResourceManager.GetString("Error_CompanyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Водитель с указанным Id не найден.
        /// </summary>
        internal static string Error_DriverNotFound {
            get {
                return ResourceManager.GetString("Error_DriverNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ТС с указанным гос.номером уже существует.
        /// </summary>
        internal static string Error_GovNumberExists {
            get {
                return ResourceManager.GetString("Error_GovNumberExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно добавить компанию. .
        /// </summary>
        internal static string Error_ImpossibleAddCompany {
            get {
                return ResourceManager.GetString("Error_ImpossibleAddCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно добавить водителя. .
        /// </summary>
        internal static string Error_ImpossibleAddDriver {
            get {
                return ResourceManager.GetString("Error_ImpossibleAddDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно зарегистрировать пользователя. .
        /// </summary>
        internal static string Error_ImpossibleAddUser {
            get {
                return ResourceManager.GetString("Error_ImpossibleAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно добавить ТС. .
        /// </summary>
        internal static string Error_ImpossibleAddVehicle {
            get {
                return ResourceManager.GetString("Error_ImpossibleAddVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно удалить компанию. .
        /// </summary>
        internal static string Error_ImpossibleDeleteCompany {
            get {
                return ResourceManager.GetString("Error_ImpossibleDeleteCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно удалить водителя. .
        /// </summary>
        internal static string Error_ImpossibleDeleteDriver {
            get {
                return ResourceManager.GetString("Error_ImpossibleDeleteDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно удалить пользователя. .
        /// </summary>
        internal static string Error_ImpossibleDeleteUser {
            get {
                return ResourceManager.GetString("Error_ImpossibleDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно удалить ТС. .
        /// </summary>
        internal static string Error_ImpossibleDeleteVehicle {
            get {
                return ResourceManager.GetString("Error_ImpossibleDeleteVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно скрыть компанию. .
        /// </summary>
        internal static string Error_ImpossibleRemoveCompany {
            get {
                return ResourceManager.GetString("Error_ImpossibleRemoveCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно скрыть водителя. .
        /// </summary>
        internal static string Error_ImpossibleRemoveDriver {
            get {
                return ResourceManager.GetString("Error_ImpossibleRemoveDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно скрыть пользователя. .
        /// </summary>
        internal static string Error_ImpossibleRemoveUser {
            get {
                return ResourceManager.GetString("Error_ImpossibleRemoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно скрыть ТС. .
        /// </summary>
        internal static string Error_ImpossibleRemoveVehicle {
            get {
                return ResourceManager.GetString("Error_ImpossibleRemoveVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно обновить компанию. .
        /// </summary>
        internal static string Error_ImpossibleUpdateCompany {
            get {
                return ResourceManager.GetString("Error_ImpossibleUpdateCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно обновить водителя. .
        /// </summary>
        internal static string Error_ImpossibleUpdateDriver {
            get {
                return ResourceManager.GetString("Error_ImpossibleUpdateDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно обновить пользователя. .
        /// </summary>
        internal static string Error_ImpossibleUpdateUser {
            get {
                return ResourceManager.GetString("Error_ImpossibleUpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно обновить ТС. .
        /// </summary>
        internal static string Error_ImpossibleUpdateVehicle {
            get {
                return ResourceManager.GetString("Error_ImpossibleUpdateVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь с указанным Логином уже существует.
        /// </summary>
        internal static string Error_LoginExists {
            get {
                return ResourceManager.GetString("Error_LoginExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь с указанным Логином не найден.
        /// </summary>
        internal static string Error_UserNotFound {
            get {
                return ResourceManager.GetString("Error_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ТС с указанным id не найдено.
        /// </summary>
        internal static string Error_VehicleNotFound {
            get {
                return ResourceManager.GetString("Error_VehicleNotFound", resourceCulture);
            }
        }
    }
}
