//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManager.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransportManager.Data.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компания с указанным CompanyId уже существует.
        /// </summary>
        internal static string Error_CompanyIdExists {
            get {
                return ResourceManager.GetString("Error_CompanyIdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компания с указанным CompanyId не найдена.
        /// </summary>
        internal static string Error_CompanyNotFound {
            get {
                return ResourceManager.GetString("Error_CompanyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Водитель с указанным Id не найден.
        /// </summary>
        internal static string Error_DriverNotFound {
            get {
                return ResourceManager.GetString("Error_DriverNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ТС с указанным гос.номером уже существует.
        /// </summary>
        internal static string Error_GovNumberExists {
            get {
                return ResourceManager.GetString("Error_GovNumberExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно добавить компанию. .
        /// </summary>
        internal static string Error_ImpossibleAddCompany {
            get {
                return ResourceManager.GetString("Error_ImpossibleAddCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно добавить водителя. .
        /// </summary>
        internal static string Error_ImpossibleAddDriver {
            get {
                return ResourceManager.GetString("Error_ImpossibleAddDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно зарегистрировать пользователя. .
        /// </summary>
        internal static string Error_ImpossibleAddUser {
            get {
                return ResourceManager.GetString("Error_ImpossibleAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно добавить ТС. .
        /// </summary>
        internal static string Error_ImpossibleAddVehicle {
            get {
                return ResourceManager.GetString("Error_ImpossibleAddVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно удалить компанию. .
        /// </summary>
        internal static string Error_ImpossibleDeleteCompany {
            get {
                return ResourceManager.GetString("Error_ImpossibleDeleteCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно удалить водителя. .
        /// </summary>
        internal static string Error_ImpossibleDeleteDriver {
            get {
                return ResourceManager.GetString("Error_ImpossibleDeleteDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно удалить пользователя. .
        /// </summary>
        internal static string Error_ImpossibleDeleteUser {
            get {
                return ResourceManager.GetString("Error_ImpossibleDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно удалить ТС. .
        /// </summary>
        internal static string Error_ImpossibleDeleteVehicle {
            get {
                return ResourceManager.GetString("Error_ImpossibleDeleteVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно скрыть компанию. .
        /// </summary>
        internal static string Error_ImpossibleRemoveCompany {
            get {
                return ResourceManager.GetString("Error_ImpossibleRemoveCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно скрыть водителя. .
        /// </summary>
        internal static string Error_ImpossibleRemoveDriver {
            get {
                return ResourceManager.GetString("Error_ImpossibleRemoveDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно скрыть пользователя. .
        /// </summary>
        internal static string Error_ImpossibleRemoveUser {
            get {
                return ResourceManager.GetString("Error_ImpossibleRemoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно скрыть ТС. .
        /// </summary>
        internal static string Error_ImpossibleRemoveVehicle {
            get {
                return ResourceManager.GetString("Error_ImpossibleRemoveVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно обновить компанию. .
        /// </summary>
        internal static string Error_ImpossibleUpdateCompany {
            get {
                return ResourceManager.GetString("Error_ImpossibleUpdateCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно обновить водителя. .
        /// </summary>
        internal static string Error_ImpossibleUpdateDriver {
            get {
                return ResourceManager.GetString("Error_ImpossibleUpdateDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно обновить пользователя. .
        /// </summary>
        internal static string Error_ImpossibleUpdateUser {
            get {
                return ResourceManager.GetString("Error_ImpossibleUpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно обновить ТС. .
        /// </summary>
        internal static string Error_ImpossibleUpdateVehicle {
            get {
                return ResourceManager.GetString("Error_ImpossibleUpdateVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с указанным Логином уже существует.
        /// </summary>
        internal static string Error_LoginExists {
            get {
                return ResourceManager.GetString("Error_LoginExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с указанным Логином не найден.
        /// </summary>
        internal static string Error_UserNotFound {
            get {
                return ResourceManager.GetString("Error_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ТС с указанным id не найдено.
        /// </summary>
        internal static string Error_VehicleNotFound {
            get {
                return ResourceManager.GetString("Error_VehicleNotFound", resourceCulture);
            }
        }
    }
}